/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package reportes;

import java.awt.Color;
import java.awt.GridBagLayout;
import java.text.ParseException;
import reportes.ControlReporte;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import misoft.VistaVentanaPrincipal;
import reportes.ModeloArticulo;

/**
 *
 * @author Administrator
 */
public class VistaReportes extends javax.swing.JPanel {

    /**
     * Creates new form VistaReportes
     */
    public VistaReportes() {
        initComponents();
        VistaVentanaPrincipal texto = new VistaVentanaPrincipal();
        texto.setTitle("reportes");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btArticulos = new javax.swing.JButton();
        btMovimientos = new javax.swing.JButton();
        btReporteVentas = new javax.swing.JButton();
        btCorte = new javax.swing.JButton();
        panelEtiqueta = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        panelRangos = new javax.swing.JPanel();

        setToolTipText("Reportes");
        setAlignmentX(20.0F);
        setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        setMinimumSize(new java.awt.Dimension(2147483647, 2147483647));
        setName("panelReportes"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1200, 1200));

        btArticulos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btArticulos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reporteAlmacen.png"))); // NOI18N
        btArticulos.setText("Reporte Almacén");
        btArticulos.setMaximumSize(new java.awt.Dimension(300, 50));
        btArticulos.setMinimumSize(new java.awt.Dimension(300, 50));
        btArticulos.setPreferredSize(new java.awt.Dimension(300, 50));
        btArticulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btArticulosActionPerformed(evt);
            }
        });
        add(btArticulos);

        btMovimientos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btMovimientos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/movimientosAlmacen.png"))); // NOI18N
        btMovimientos.setText("Reporte Movimientos");
        btMovimientos.setMaximumSize(new java.awt.Dimension(300, 50));
        btMovimientos.setMinimumSize(new java.awt.Dimension(300, 50));
        btMovimientos.setPreferredSize(new java.awt.Dimension(300, 50));
        btMovimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMovimientosActionPerformed(evt);
            }
        });
        add(btMovimientos);

        btReporteVentas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btReporteVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reporteVenta.png"))); // NOI18N
        btReporteVentas.setText("Reporte de Ventas");
        btReporteVentas.setMaximumSize(new java.awt.Dimension(300, 50));
        btReporteVentas.setMinimumSize(new java.awt.Dimension(300, 50));
        btReporteVentas.setPreferredSize(new java.awt.Dimension(300, 50));
        btReporteVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReporteVentasActionPerformed(evt);
            }
        });
        add(btReporteVentas);

        btCorte.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btCorte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reporteCorteCaja.png"))); // NOI18N
        btCorte.setText("Reporte Corte de Caja");
        btCorte.setMaximumSize(new java.awt.Dimension(300, 50));
        btCorte.setMinimumSize(new java.awt.Dimension(300, 50));
        btCorte.setPreferredSize(new java.awt.Dimension(300, 50));
        btCorte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verCorteCaja(evt);
            }
        });
        btCorte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCorteActionPerformed(evt);
            }
        });
        add(btCorte);

        panelEtiqueta.setMinimumSize(new java.awt.Dimension(2000, 100));
        panelEtiqueta.setPreferredSize(new java.awt.Dimension(2000, 100));
        panelEtiqueta.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/img30x30/facturacion_electronica.png"))); // NOI18N
        jLabel1.setText("Reportes");
        panelEtiqueta.add(jLabel1, new java.awt.GridBagConstraints());

        add(panelEtiqueta);

        jSeparator2.setMaximumSize(new java.awt.Dimension(2000, 10));
        jSeparator2.setMinimumSize(new java.awt.Dimension(580, 10));
        jSeparator2.setPreferredSize(new java.awt.Dimension(1300, 10));
        add(jSeparator2);

        panelRangos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelRangos.setMaximumSize(new java.awt.Dimension(1200, 380));
        panelRangos.setMinimumSize(new java.awt.Dimension(1200, 380));
        panelRangos.setPreferredSize(new java.awt.Dimension(1200, 420));
        panelRangos.setLayout(new java.awt.GridBagLayout());
        add(panelRangos);
    }// </editor-fold>//GEN-END:initComponents

    private void btCorteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCorteActionPerformed

        panelRangos.removeAll();
        this.repaint();
        
    }//GEN-LAST:event_btCorteActionPerformed
    
    
    private void btArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btArticulosActionPerformed
        // TODO add your handling code here:
        //Generar tabla de articulos
     
        panelRangos.removeAll();
        panelRangos.revalidate();
        VistaReporteAlmacen vista = new VistaReporteAlmacen();
        panelRangos.add(vista);
        vista.show();
        this.repaint();
        btArticulos.setBackground(Color.gray);
        btMovimientos.setBackground(Color.lightGray);
        btReporteVentas.setBackground(Color.lightGray);
        btCorte.setBackground(Color.lightGray);
    }//GEN-LAST:event_btArticulosActionPerformed

    private void btReporteVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReporteVentasActionPerformed
        // TODO add your handling code here:
        panelRangos.removeAll();
        panelRangos.revalidate();
        VistaReporteVentasGeneral vista = new VistaReporteVentasGeneral();
        panelRangos.add(vista);
        vista.show();
        this.repaint();
        btArticulos.setBackground(Color.lightGray);
        btMovimientos.setBackground(Color.lightGray);
        btReporteVentas.setBackground(Color.gray);
        btCorte.setBackground(Color.lightGray);
        
    

    }//GEN-LAST:event_btReporteVentasActionPerformed

    private void verCorteCaja(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verCorteCaja
        // TODO add your handling code here:
        
             
        panelRangos.removeAll();
        panelRangos.revalidate();
        VistaReporteCorte vista = new VistaReporteCorte();
        panelRangos.add(vista);
        vista.show();
        //vista.setVisible(true);
        //jpRangos.revalidate();
        btArticulos.setBackground(Color.lightGray);
        btMovimientos.setBackground(Color.lightGray);
        btReporteVentas.setBackground(Color.lightGray);
        btCorte.setBackground(Color.gray);
        
    }//GEN-LAST:event_verCorteCaja

    private void btMovimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMovimientosActionPerformed
        try {
            panelRangos.removeAll();
            panelRangos.revalidate();
            VistaReporteMovimientos vista = new VistaReporteMovimientos();
            panelRangos.add(vista);
            vista.show();
            this.repaint();
            btArticulos.setBackground(Color.lightGray);
            btReporteVentas.setBackground(Color.lightGray);
            btCorte.setBackground(Color.lightGray);
            btMovimientos.setBackground(Color.gray);
            
        } catch (ParseException ex) {
            Logger.getLogger(VistaReportes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btMovimientosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btArticulos;
    private javax.swing.JButton btCorte;
    private javax.swing.JButton btMovimientos;
    private javax.swing.JButton btReporteVentas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel panelEtiqueta;
    private javax.swing.JPanel panelRangos;
    // End of variables declaration//GEN-END:variables
}
