/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package venta;

import articulo.Articulo;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Eddie
 */
public class VistaRealizarCobro extends javax.swing.JFrame {

    public ArrayList carrito;
    
    /**
     * Creates new form VistaRealizarCobro
     */
    public VistaRealizarCobro(ArrayList carrito) {
        initComponents();
        this.carrito =  carrito;
    }
    
    public VistaRealizarCobro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbSubTotal = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbIva = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbTotal = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbCambio = new javax.swing.JLabel();
        btCobrar = new javax.swing.JButton();
        txEfectivo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btContinuar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Realizar Cobro");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.ABOVE_BASELINE_LEADING;
        gridBagConstraints.insets = new java.awt.Insets(11, 8, 11, 8);
        getContentPane().add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Sub Total:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.ABOVE_BASELINE_LEADING;
        gridBagConstraints.insets = new java.awt.Insets(11, 8, 11, 8);
        getContentPane().add(jLabel2, gridBagConstraints);

        lbSubTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbSubTotal.setText("0.0 $");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.ABOVE_BASELINE_LEADING;
        gridBagConstraints.insets = new java.awt.Insets(11, 8, 11, 8);
        getContentPane().add(lbSubTotal, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Iva:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.ABOVE_BASELINE_LEADING;
        gridBagConstraints.insets = new java.awt.Insets(11, 8, 11, 8);
        getContentPane().add(jLabel4, gridBagConstraints);

        lbIva.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbIva.setText("0.0 $");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.ABOVE_BASELINE_LEADING;
        gridBagConstraints.insets = new java.awt.Insets(11, 8, 11, 8);
        getContentPane().add(lbIva, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Total:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.ABOVE_BASELINE_LEADING;
        gridBagConstraints.insets = new java.awt.Insets(11, 8, 11, 8);
        getContentPane().add(jLabel6, gridBagConstraints);

        lbTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbTotal.setText("0.0 $");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.ABOVE_BASELINE_LEADING;
        gridBagConstraints.insets = new java.awt.Insets(11, 8, 11, 8);
        getContentPane().add(lbTotal, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Efectivo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.ABOVE_BASELINE_LEADING;
        gridBagConstraints.insets = new java.awt.Insets(11, 8, 11, 8);
        getContentPane().add(jLabel8, gridBagConstraints);

        lbCambio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbCambio.setText("0.0 $");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.ABOVE_BASELINE_LEADING;
        gridBagConstraints.insets = new java.awt.Insets(11, 8, 11, 8);
        getContentPane().add(lbCambio, gridBagConstraints);

        btCobrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btCobrar.setText("Cobrar");
        btCobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCobrarActionPerformed(evt);
            }
        });
        btCobrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btCobrarKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.ABOVE_BASELINE_LEADING;
        gridBagConstraints.insets = new java.awt.Insets(11, 8, 11, 8);
        getContentPane().add(btCobrar, gridBagConstraints);

        txEfectivo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txEfectivo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txEfectivoKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.ABOVE_BASELINE_LEADING;
        gridBagConstraints.insets = new java.awt.Insets(11, 8, 11, 8);
        getContentPane().add(txEfectivo, gridBagConstraints);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Cambio:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.ABOVE_BASELINE_LEADING;
        gridBagConstraints.insets = new java.awt.Insets(11, 8, 11, 8);
        getContentPane().add(jLabel10, gridBagConstraints);

        btContinuar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btContinuar.setText("Continuar");
        btContinuar.setEnabled(false);
        btContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btContinuarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.ABOVE_BASELINE_LEADING;
        gridBagConstraints.insets = new java.awt.Insets(11, 8, 11, 8);
        getContentPane().add(btContinuar, gridBagConstraints);

        btCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.ABOVE_BASELINE_LEADING;
        gridBagConstraints.insets = new java.awt.Insets(11, 8, 11, 8);
        getContentPane().add(btCancelar, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCobrarActionPerformed
        // TODO add your handling code here:
        
        Float efectivo = null;
        Float cambio = null;
        Float total = calcularCosto();
        DecimalFormat decimal = new DecimalFormat("#.##");
         
        try{
            efectivo = Float.parseFloat(txEfectivo.getText());
            
            if(efectivo>0 && efectivo > total){
            cambio = Float.parseFloat(decimal.format(efectivo)) - total;
            cambio = Float.parseFloat(decimal.format(cambio));
            }
            
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Cantidad introducida incorrecta");
        }
        
       
        if(efectivo!=null && cambio!=null && cambio>=(0.0f)){
        ControlVenta ctrVenta = new ControlVenta();
      if(ctrVenta.realizarVenta(carrito)){
          
          btCancelar.setEnabled(false);
          btCobrar.setEnabled(false);
          txEfectivo.setEnabled(false);
          JOptionPane.showMessageDialog(this, "Venta Realizada con Exito");
         btContinuar.setEnabled(true);
         btContinuar.requestFocus();
         
         lbCambio.setText(""+(cambio)+" $");

      }
      else
          JOptionPane.showMessageDialog(this, "Ocurrio un error al momento de realizar la venta");
      
        }
        else{
             JOptionPane.showMessageDialog(this, "Efectivo insuficiente o incorrecto");
             
        }
        
    }//GEN-LAST:event_btCobrarActionPerformed

    
    public Float calcularCosto(){
        
        Integer cantidad_articulos = carrito.size();
        Float subTotal = 0.0f;
        Float subSubTotal = 0.0f;
        Float iva = 0.0f;
        
         for(int x=0; x<cantidad_articulos; x++)
          {
              
             Object articuloTmp = carrito.get(x);
             Object[] thisArticulo = ((Object[]) articuloTmp); 
              
          
          subTotal += ((Articulo)thisArticulo[0]).getPrecioVenta()*((Integer)thisArticulo[1]).intValue();

          
          }
         
         subSubTotal = (subTotal*100)/111;
         iva =subTotal-subSubTotal;
         
         DecimalFormat decimal = new DecimalFormat("#.##");
         
        lbSubTotal.setText(""+decimal.format(subSubTotal)+" $");
        lbIva.setText(""+decimal.format(iva)+" $");
        lbTotal.setText(""+decimal.format(subTotal)+" $");
        
        return Float.parseFloat(decimal.format(subTotal));
    }
    
    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btContinuarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btContinuarActionPerformed

    private void txEfectivoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txEfectivoKeyPressed
        // TODO add your handling code here:
        
         int key=evt.getKeyCode();

        
        if(key==KeyEvent.VK_ESCAPE)
        { 
          this.dispose();
        }
        else
            if(key==KeyEvent.VK_ENTER)
                { 
                   btCobrarActionPerformed(null);
                }

        
    }//GEN-LAST:event_txEfectivoKeyPressed

    private void btCobrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btCobrarKeyPressed
        // TODO add your handling code here:
        
         int key=evt.getKeyCode();

             if(evt.getSource()==btContinuar)
            {
                if(key==KeyEvent.VK_ENTER)
                { 
                   this.dispose();
                }
            }
        
    }//GEN-LAST:event_btCobrarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaRealizarCobro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaRealizarCobro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaRealizarCobro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaRealizarCobro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaRealizarCobro().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btCobrar;
    private javax.swing.JButton btContinuar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lbCambio;
    private javax.swing.JLabel lbIva;
    private javax.swing.JLabel lbSubTotal;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JTextField txEfectivo;
    // End of variables declaration//GEN-END:variables
}
