/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package venta;

import articulo.Articulo;
import articulo.ControlArticulo;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.RowSorter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Eddie
 */
public class VistaCancelarVenta extends javax.swing.JFrame {

    public Long venta = null;
    
    /**
     * Creates new form VistaCancelarVenta
     */
    public VistaCancelarVenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txBusqueda = new javax.swing.JTextField();
        btBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbArticulos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbSubTotal = new javax.swing.JLabel();
        lbi = new javax.swing.JLabel();
        lbIva = new javax.swing.JLabel();
        lbt = new javax.swing.JLabel();
        lbTotal = new javax.swing.JLabel();
        btCancelarVenta = new javax.swing.JButton();
        btCancelarOperacion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel1.setText("Cancelar Venta");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        getContentPane().add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Numero de Venta:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.ABOVE_BASELINE_LEADING;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        getContentPane().add(jLabel2, gridBagConstraints);

        txBusqueda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txBusquedaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.ABOVE_BASELINE_LEADING;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        getContentPane().add(txBusqueda, gridBagConstraints);

        btBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NuevasImagenes/1386942888_search.png"))); // NOI18N
        btBuscar.setText("Buscar Venta");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.ABOVE_BASELINE_LEADING;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        getContentPane().add(btBuscar, gridBagConstraints);

        tbArticulos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbArticulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo Articulo", "Descripcion", "Cantidad", "Precio Venta"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbArticulos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbArticulos);
        tbArticulos.getColumnModel().getColumn(0).setResizable(false);
        tbArticulos.getColumnModel().getColumn(1).setResizable(false);
        tbArticulos.getColumnModel().getColumn(2).setResizable(false);
        tbArticulos.getColumnModel().getColumn(3).setResizable(false);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jScrollPane1, gridBagConstraints);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("SubTotal:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.01;
        gridBagConstraints.insets = new java.awt.Insets(8, 11, 8, 11);
        jPanel1.add(jLabel3, gridBagConstraints);

        lbSubTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbSubTotal.setText("$ 0.0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.01;
        gridBagConstraints.insets = new java.awt.Insets(8, 11, 8, 11);
        jPanel1.add(lbSubTotal, gridBagConstraints);

        lbi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbi.setText("Iva:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.01;
        gridBagConstraints.insets = new java.awt.Insets(8, 11, 8, 11);
        jPanel1.add(lbi, gridBagConstraints);

        lbIva.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbIva.setText("$ 0.0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.01;
        gridBagConstraints.insets = new java.awt.Insets(8, 11, 8, 11);
        jPanel1.add(lbIva, gridBagConstraints);

        lbt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbt.setText("Total:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.01;
        gridBagConstraints.insets = new java.awt.Insets(8, 11, 8, 11);
        jPanel1.add(lbt, gridBagConstraints);

        lbTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbTotal.setText(" $ 0.0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.01;
        gridBagConstraints.insets = new java.awt.Insets(8, 11, 8, 11);
        jPanel1.add(lbTotal, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanel1, gridBagConstraints);

        btCancelarVenta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btCancelarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NuevasImagenes/almacen.png"))); // NOI18N
        btCancelarVenta.setText("Cancelar Venta");
        btCancelarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarVentaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        getContentPane().add(btCancelarVenta, gridBagConstraints);

        btCancelarOperacion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btCancelarOperacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/img20x20/cancelar_1.jpg"))); // NOI18N
        btCancelarOperacion.setText("Cancelar Operacion");
        btCancelarOperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarOperacionActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(btCancelarOperacion, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txBusquedaActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        // TODO add your handling code here:
        
        //String donde almacenar el texto a buscar y variables aux
        Long idVenta = null;
        String numeroVenta = txBusqueda.getText();
        venta = null;
        
        
        //Validaciones de caja texto y de la venta exista
        if(numeroVenta.length()<=0){
             JOptionPane.showMessageDialog(this,"Hubo un error en la operacion");
        }
        
        
         try{
           idVenta = Long.parseLong(numeroVenta); 
           venta = idVenta;
    }catch(NumberFormatException e)
        {
            //errorLog+="- El codigo de articulo tiene un formato incorrecto \n";
        }
        
         
         if(idVenta == null){
              JOptionPane.showMessageDialog(this,"El numero de venta es erroneo, solo se permiten numeros");
             return;
         }else
             if(idVenta<0 || numeroVenta.contains("+") || numeroVenta.contains("-")){
            //errorLog += "- Codigo de Articulo no es valido, solo son permitidos numeros \n";
                 JOptionPane.showMessageDialog(this,"El numero de venta es erroneo, solo se permiten numeros");
                 return;
        }
         
        //Iniciamos controlador
        ControlArticulo ctrArticulo = new ControlArticulo();
        
        //Iniciamos objectos donde guardaremos los resultados de busqueda
        Object[] articulos = null;
        
        //Iniciamos objetos clase
        Venta ventaBuscar = new Venta(true);
        ArticuloVenta articulosVentaBuscar = new ArticuloVenta(true);
        
        //Buscamos primero venta
        ventaBuscar.setIdVenta(idVenta);
        Boolean ventaValida = false;
        ventaValida = ventaBuscar.buscarBD();
        //Validamos que la venta no ha sido cancelada antes por completo
            if(ventaValida)
                if(ventaBuscar.getCancelado()){
                        ventaValida = false;
                    }
        
        //Validamos venta
        if(!ventaValida)
        {
            JOptionPane.showMessageDialog(this,"La venta no ha sido encontrada");
                 return;
        }
        

        //Buscamos articulos venta 
      Object[][] opciones = new Object[][] {{"idVenta","=",idVenta}};
      articulos = articulosVentaBuscar.buscarBD("all", opciones);
        
        
            
        
        if(articulos.length<=0)
            JOptionPane.showMessageDialog(this,"no se encontraron articulos en esta venta");
        else
        {
            llenarTabla(articulos);
            calcularCosto(articulos);
        }
        
        
    }//GEN-LAST:event_btBuscarActionPerformed

    private void btCancelarOperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarOperacionActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btCancelarOperacionActionPerformed

    private void btCancelarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarVentaActionPerformed
        // TODO add your handling code here:
        
        
        
        
        
        if(this.venta==null){
            JOptionPane.showMessageDialog(this,"No has seleccionado venta");
            return;
        }
            
        //Iniciamos controladores y objetos
        ControlVenta ctrVenta = new ControlVenta();
       Boolean ventaCancelada = ctrVenta.cancelarVenta(this.venta);
        
        if(ventaCancelada){
             JOptionPane.showMessageDialog(this,"La venta ha sido cancelada \n"+"Devolver la cantidad de:");
        }else{
             JOptionPane.showMessageDialog(this,"La venta no se pudo cancelar satisfactoriamente");
        }
        
    }//GEN-LAST:event_btCancelarVentaActionPerformed

    private void llenarTabla(Object[] articulos) {
        
        DefaultTableModel datos = (DefaultTableModel) tbArticulos.getModel();
        datos.setRowCount(0);
         
        for(Object thisArticulo: articulos)
          {
              //Inicio variables temporales
              Articulo datosArticulo = new Articulo(true);
              Integer cantidadTemp = 0;
              
              datosArticulo.setIdArticulo(((ArticuloVenta)thisArticulo).getIdArticulo());
              datosArticulo.buscarBD();
              
              if(((ArticuloVenta)thisArticulo).getDevolucion())
              cantidadTemp = ((ArticuloVenta)thisArticulo).getCantidad()-((ArticuloVenta)thisArticulo).getCantidadDevuelto();
              else
              cantidadTemp = ((ArticuloVenta)thisArticulo).getCantidad();
              
          datos.addRow(new Object[] {
          datosArticulo.getCodigoArticulo(),
          datosArticulo.getDescripcion()+" -- "+datosArticulo.getCantidadUnidad()+" "+datosArticulo.getUnidad(),
          cantidadTemp,
          ((ArticuloVenta)thisArticulo).getPrecioVenta()
          
          });
        
        RowSorter<TableModel> sorter = new TableRowSorter<TableModel>(tbArticulos.getModel());
          
        tbArticulos.setRowSorter(sorter);
          }
    }
    
    public void calcularCosto(Object[] articulos){
        
        Integer cantidad_articulos = articulos.length;
        Float subTotal = 0.0f;
        Float subSubTotal = 0.0f;
        Float iva = 0.0f;
        
         for(int x=0; x<cantidad_articulos; x++)
          {
              
             
             ArticuloVenta thisArticulo = ((ArticuloVenta) articulos[x]); 
              
             Integer cantidadTmp = 0;
             
             if(thisArticulo.getDevolucion()){
                 cantidadTmp = thisArticulo.getCantidad()-thisArticulo.getCantidadDevuelto();
             }
             else
                 cantidadTmp = thisArticulo.getCantidad();
          
          subTotal += (thisArticulo.getPrecioVenta()*cantidadTmp);
          

          }
         
         subSubTotal = (subTotal*100)/111;//Meter iva
         iva =subTotal-subSubTotal;
         
         DecimalFormat decimal = new DecimalFormat("#.##");
         
        lbSubTotal.setText("$ "+decimal.format(subSubTotal));
        lbIva.setText("$ "+decimal.format(iva));
        lbTotal.setText("$ "+decimal.format(subTotal));
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaCancelarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaCancelarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaCancelarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaCancelarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaCancelarVenta().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btCancelarOperacion;
    private javax.swing.JButton btCancelarVenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbIva;
    private javax.swing.JLabel lbSubTotal;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JLabel lbi;
    private javax.swing.JLabel lbt;
    private javax.swing.JTable tbArticulos;
    private javax.swing.JTextField txBusqueda;
    // End of variables declaration//GEN-END:variables
}
