/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package usuario;

/**
 *
 * @author USUARIO
 */
public class VistaEdicionUsuario2 extends javax.swing.JPanel {
    private String txBuscar;

    /**
     * Creates new form VistaEdicionUsuario2
     */
    public VistaEdicionUsuario2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jUsuarios = new javax.swing.JLabel();
        btEditarUsuario = new javax.swing.JButton();

        jUsuarios.setText("Editar Usuario");

        btEditarUsuario.setText("Aceptar");
        btEditarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarUsuario(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btEditarUsuario)
                    .addComponent(jUsuarios))
                .addContainerGap(280, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jUsuarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 228, Short.MAX_VALUE)
                .addComponent(btEditarUsuario)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void editarUsuario(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarUsuario
           VistaConsultaGeneralUsuarios vista = new VistaConsultaGeneralUsuarios(this.txBuscar);
           this.removeAll();
           //this.setBorder(javax.swing.BorderFactory.createEtchedBorder());
           this.setLayout(new java.awt.BorderLayout());
           this.add(vista);
           vista.show();
           this.revalidate();
           this.repaint();
        
// TODO add your handling code here:
    }//GEN-LAST:event_editarUsuario


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEditarUsuario;
    private javax.swing.JLabel jUsuarios;
    // End of variables declaration//GEN-END:variables
}
