package login;


import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import misoft.VistaVentanaPrincipal;
import usuario.ControlUsuario;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author NOE
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        txUsuario = new javax.swing.JTextField();
        RealizarLogin = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txContraseña = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        txUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txUsuarioActionPerformed(evt);
            }
        });
        txUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txUsuarioKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 245;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 4, 0, 10);
        getContentPane().add(txUsuario, gridBagConstraints);

        RealizarLogin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        RealizarLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/aceptar1.png"))); // NOI18N
        RealizarLogin.setText("Aceptar");
        RealizarLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                realizarLogin(evt);
            }
        });
        RealizarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RealizarLoginActionPerformed(evt);
            }
        });
        RealizarLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                RealizarLoginKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 11, 11, 0);
        getContentPane().add(RealizarLogin, gridBagConstraints);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar_1.jpg"))); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 6, 11, 10);
        getContentPane().add(jButton2, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Usuario:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipady = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 30, 0, 0);
        getContentPane().add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Password:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipady = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 10, 0, 0);
        getContentPane().add(jLabel2, gridBagConstraints);

        txContraseña.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txContraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txContraseñaKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 245;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 4, 0, 10);
        getContentPane().add(txContraseña, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void realizarLogin(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_realizarLogin

//        ControlUsuario ctrusuario = new ControlUsuario();
//        String errores="";
//        
//         errores=ctrusuario.validarDatosLogin(txUsuario.getText(),txContraseña.getText());
//         if(errores.length()>0)
//       { 
//           JOptionPane.showMessageDialog(this,errores);
//      
//        }
//            else
//        if(ctrusuario.realizarLogin(txUsuario.getText() ,  txContraseña.getText()))                
//                {
//                    System.out.println("Se hizo login correctamente");
//                    
//                    VistaVentanaPrincipal ventanaPrincipal = new VistaVentanaPrincipal();
//                    ventanaPrincipal.setVisible(true);
//                    this.dispose();
//                    
//                }
//        else JOptionPane.showMessageDialog(this, "¡ El Usuario y/o Password es incorrecto !");
//        txUsuario.setText("");
//        txContraseña.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_realizarLogin

    private void RealizarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RealizarLoginActionPerformed
        // TODO add your handling code here:
        ControlUsuario ctrusuario = new ControlUsuario();
        String errores="";
        
         errores=ctrusuario.validarDatosLogin(txUsuario.getText(),txContraseña.getText());
         if(errores.length()>0)
       { 
           JOptionPane.showMessageDialog(this,errores);
      
        }
            else
        if(ctrusuario.realizarLogin(txUsuario.getText() ,  txContraseña.getText()))                
                {
                    System.out.println("Se hizo login correctamente");
                    
                    VistaVentanaPrincipal ventanaPrincipal = new VistaVentanaPrincipal();
                    ventanaPrincipal.setVisible(true);
                    this.dispose();
                    
                }
        else JOptionPane.showMessageDialog(this, "¡ El Usuario y/o Password es incorrecto !");
        txUsuario.setText("");
        txContraseña.setText("");
     
    }//GEN-LAST:event_RealizarLoginActionPerformed

    private void txUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txUsuarioActionPerformed

    private void RealizarLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RealizarLoginKeyPressed
        // TODO add your handling code here:
                  int key=evt.getKeyCode();
    if(evt.getSource()==RealizarLogin)
    {
        if(key==KeyEvent.VK_ENTER)
        { 
           RealizarLoginActionPerformed(null);                    
        }
    }
    }//GEN-LAST:event_RealizarLoginKeyPressed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed
        // TODO add your handling code here:
                  int key=evt.getKeyCode();
    if(evt.getSource()==jButton2)
    {
        if(key==KeyEvent.VK_ENTER)
        { 
           jButton2ActionPerformed(null);                    
        }
    }
    }//GEN-LAST:event_jButton2KeyPressed

    private void txUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txUsuarioKeyPressed
        // TODO add your handling code here:
                int key=evt.getKeyCode();
    if(evt.getSource()==txUsuario)
    {
        if(key==KeyEvent.VK_ENTER)
        { 
           RealizarLoginActionPerformed(null);                    
        }
    }   
    }//GEN-LAST:event_txUsuarioKeyPressed

    private void txContraseñaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txContraseñaKeyPressed
        // TODO add your handling code here:
                   int key=evt.getKeyCode();
    if(evt.getSource()==txContraseña)
    {
        if(key==KeyEvent.VK_ENTER)
        { 
           RealizarLoginActionPerformed(null);                    
        }
    }
    }//GEN-LAST:event_txContraseñaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RealizarLogin;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField txContraseña;
    private javax.swing.JTextField txUsuario;
    // End of variables declaration//GEN-END:variables
}
