/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package articulo;

import java.awt.LayoutManager;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import usuario.ControlUsuario;

/**
 *
 * @author Eddie
 */
public class VistaRegistrarArticulo extends javax.swing.JPanel {

    /**
     * Creates new form VistaAltaArticulos
     */
    
    private String textoBusqueda;
    
    
    
    public VistaRegistrarArticulo() {
        initComponents();
        this.textoBusqueda ="";
          
    }
    
    public VistaRegistrarArticulo(String textoBusqueda) {
        initComponents();
        this.textoBusqueda = "";
         this.textoBusqueda = textoBusqueda;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        txCodigoArticulo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txDescripcion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txProveedor = new javax.swing.JTextField();
        btAceptarAlta = new javax.swing.JButton();
        btCancelarAlta = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txcantidadUnidad = new javax.swing.JTextField();
        comboBoxUnidad = new javax.swing.JComboBox();

        setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Código Artículo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jLabel1, gridBagConstraints);

        txCodigoArticulo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txCodigoArticulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txCodigoArticuloKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(txCodigoArticulo, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Descripción:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jLabel2, gridBagConstraints);

        txDescripcion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txDescripcionActionPerformed(evt);
            }
        });
        txDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txDescripcionKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(txDescripcion, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Proveedor:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jLabel5, gridBagConstraints);

        txProveedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txProveedorKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(txProveedor, gridBagConstraints);

        btAceptarAlta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btAceptarAlta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/img20x20/aceptar1.png"))); // NOI18N
        btAceptarAlta.setText("Aceptar");
        btAceptarAlta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                realizarRegistroArticulo(evt);
            }
        });
        btAceptarAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAceptarAltaActionPerformed(evt);
            }
        });
        btAceptarAlta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btAceptarAltaKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(btAceptarAlta, gridBagConstraints);

        btCancelarAlta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btCancelarAlta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/img20x20/cancelar_1.jpg"))); // NOI18N
        btCancelarAlta.setText("Cancelar");
        btCancelarAlta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarRegistro(evt);
            }
        });
        btCancelarAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarAltaActionPerformed(evt);
            }
        });
        btCancelarAlta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btCancelarAltaKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(btCancelarAlta, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Alta Artículos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jLabel6, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Cantidad de Unidad");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jLabel3, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Unidad");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jLabel4, gridBagConstraints);

        txcantidadUnidad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txcantidadUnidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txcantidadUnidadKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        add(txcantidadUnidad, gridBagConstraints);

        comboBoxUnidad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboBoxUnidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pieza(s)", "Unidad(es)", "Mililitro(s) ", "Litro(s)", "Gramo(s)", "Kilogramo(s)", "Centimetro(s)", "Metro(s)" }));
        comboBoxUnidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                comboBoxUnidadKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weighty = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 0, 0);
        add(comboBoxUnidad, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void txDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txDescripcionActionPerformed

    private void realizarRegistroArticulo(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_realizarRegistroArticulo
//        // TODO add your handling code here:
//        
//        //barraEstado.setText("Alta Articulos: Guardando");
//        
//        String errorString = "";
//        
//       ControlArticulo ctrArticulos = new ControlArticulo();
//       String errors = "";
//       
//       //ControlUsuario ctrUsuario =new ControlUsuario();
//       
//       //Long idUsuario = ctrUsuario.obtenerUsuarioActual(this);
//       
//       //Boolean autorizado = ctrUsuario.autorizarOperacion(idUsuario);
//       
//       //if(!autorizado)
//         //  errors += "No estas autorizado";
//    
//    
//       errors += ctrArticulos.validaDatosArticulo(txCodigoArticulo.getText(), txDescripcion.getText(),txProveedor.getText(), txcantidadUnidad.getText(), (String) comboBoxUnidad.getSelectedItem() );
//    
//       
//       if(errors.length()>0)
//       { JOptionPane.showMessageDialog(this,errors);
//        //barraEstado.setText("Alta Articulos: En Espera");
//       }
//       else
//       {
//          Integer status = ctrArticulos.realizarRegistroArticulo(txCodigoArticulo.getText(), txDescripcion.getText(), txProveedor.getText(), txcantidadUnidad.getText(), (String) comboBoxUnidad.getSelectedItem() );
//    
//           if(status==1)
//           {
//           
//            Object opciones[] = { "SI", "NO" };    
//         Integer seleccion = JOptionPane.showOptionDialog(this, "El articulo se registro con exito, deceas registrar otro mas?", "Atencion!",
//        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, opciones, opciones[1]);
//    
//            
//            
//            if(seleccion == JOptionPane.YES_OPTION)
//            {
//                txCodigoArticulo.setText("");
//                txDescripcion.setText("");
//                txProveedor.setText("");
//            
//            }
//            else{
//                VistaConsultarArticuloEspecifico vista = new VistaConsultarArticuloEspecifico(Long.parseLong(txCodigoArticulo.getText()),textoBusqueda);
//                this.removeAll();
//                txCodigoArticulo.setText("");
//                txDescripcion.setText("");
//                txProveedor.setText("");
//                this.setLayout(new java.awt.BorderLayout());
//                this.add(vista);
//                vista.show();
//                this.revalidate();
//                this.repaint();
//            }
//            
//           }
//           else
//           {
//               JOptionPane.showMessageDialog(this,"Hubo un error en la operacion");
//               //barraEstado.setText("Alta Articulos: En Espera");
//           }
//           
//       }
        
        
    }//GEN-LAST:event_realizarRegistroArticulo

    private void cancelarRegistro(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarRegistro
        // TODO add your handling code here:
        
//         VistaConsultarArticulosGeneral vista = new VistaConsultarArticulosGeneral(textoBusqueda);
//           this.removeAll();
//           //this.setBorder(javax.swing.BorderFactory.createEtchedBorder());
//           this.setLayout(new java.awt.BorderLayout());          
//           this.add(vista);
//           vista.show();
//           this.revalidate();
//           this.repaint();
//        
        
    }//GEN-LAST:event_cancelarRegistro

    private void txCodigoArticuloKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txCodigoArticuloKeyPressed
        // TODO add your handling code here:
                                 int key=evt.getKeyCode();
    if(evt.getSource()==txCodigoArticulo)
    {
        if(key==KeyEvent.VK_ENTER)
        { 
        btAceptarAltaActionPerformed(null);                    
        }
    }
    }//GEN-LAST:event_txCodigoArticuloKeyPressed

    private void btAceptarAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAceptarAltaActionPerformed
        // TODO add your handling code here:
          // TODO add your handling code here:
        
        //barraEstado.setText("Alta Articulos: Guardando");
        
        String errorString = "";
        
       ControlArticulo ctrArticulos = new ControlArticulo();
       String errors = "";
       
       //ControlUsuario ctrUsuario =new ControlUsuario();
       
       //Long idUsuario = ctrUsuario.obtenerUsuarioActual(this);
       
       //Boolean autorizado = ctrUsuario.autorizarOperacion(idUsuario);
       
       //if(!autorizado)
         //  errors += "No estas autorizado";
    
    
       errors += ctrArticulos.validaDatosArticulo(txCodigoArticulo.getText(), txDescripcion.getText(),txProveedor.getText(), txcantidadUnidad.getText(), (String) comboBoxUnidad.getSelectedItem() );
    
       
       if(errors.length()>0)
       { JOptionPane.showMessageDialog(this,errors);
        //barraEstado.setText("Alta Articulos: En Espera");
       }
       else
       {
          Integer status = ctrArticulos.realizarRegistroArticulo(txCodigoArticulo.getText(), txDescripcion.getText(), txProveedor.getText(), txcantidadUnidad.getText(), (String) comboBoxUnidad.getSelectedItem() );
    
           if(status==1)
           {
           
            Object opciones[] = { "SI", "NO" };    
         Integer seleccion = JOptionPane.showOptionDialog(this, "El articulo se registro con exito, deceas registrar otro mas?", "Atencion!",
        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, opciones, opciones[1]);
    
            
            
            if(seleccion == JOptionPane.YES_OPTION)
            {
                txCodigoArticulo.setText("");
                txDescripcion.setText("");
                txProveedor.setText("");
            
            }
            else{
                VistaConsultarArticuloEspecifico vista = new VistaConsultarArticuloEspecifico(Long.parseLong(txCodigoArticulo.getText()),textoBusqueda);
                this.removeAll();
                txCodigoArticulo.setText("");
                txDescripcion.setText("");
                txProveedor.setText("");
                this.setLayout(new java.awt.BorderLayout());
                this.add(vista);
                vista.show();
                this.revalidate();
                this.repaint();
            }
            
           }
           else
           {
               JOptionPane.showMessageDialog(this,"Hubo un error en la operacion");
               //barraEstado.setText("Alta Articulos: En Espera");
           }
           
       }
    }//GEN-LAST:event_btAceptarAltaActionPerformed

    private void txDescripcionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txDescripcionKeyPressed
        // TODO add your handling code here:
                                     int key=evt.getKeyCode();
    if(evt.getSource()==txDescripcion)
    {
        if(key==KeyEvent.VK_ENTER)
        { 
        btAceptarAltaActionPerformed(null);                    
        }
    }
    }//GEN-LAST:event_txDescripcionKeyPressed

    private void txProveedorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txProveedorKeyPressed
        // TODO add your handling code here:
                                     int key=evt.getKeyCode();
    if(evt.getSource()==txProveedor)
    {
        if(key==KeyEvent.VK_ENTER)
        { 
        btAceptarAltaActionPerformed(null);                    
        }
    }
    }//GEN-LAST:event_txProveedorKeyPressed

    private void txcantidadUnidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txcantidadUnidadKeyPressed
        // TODO add your handling code here:
                                     int key=evt.getKeyCode();
    if(evt.getSource()==txcantidadUnidad)
    {
        if(key==KeyEvent.VK_ENTER)
        { 
        btAceptarAltaActionPerformed(null);                    
        }
    }
    }//GEN-LAST:event_txcantidadUnidadKeyPressed

    private void comboBoxUnidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comboBoxUnidadKeyPressed
        // TODO add your handling code here:
                                     int key=evt.getKeyCode();
    if(evt.getSource()==comboBoxUnidad)
    {
        if(key==KeyEvent.VK_ENTER)
        { 
        btAceptarAltaActionPerformed(null);                    
        }
    }
    }//GEN-LAST:event_comboBoxUnidadKeyPressed

    private void btAceptarAltaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btAceptarAltaKeyPressed
        // TODO add your handling code here:
                                     int key=evt.getKeyCode();
    if(evt.getSource()==btAceptarAlta)
    {
        if(key==KeyEvent.VK_ENTER)
        { 
        btAceptarAltaActionPerformed(null);                    
        }
    }
    }//GEN-LAST:event_btAceptarAltaKeyPressed

    private void btCancelarAltaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btCancelarAltaKeyPressed
        // TODO add your handling code here:
                                     int key=evt.getKeyCode();
    if(evt.getSource()==btCancelarAlta)
    {
        if(key==KeyEvent.VK_ENTER)
        { 
       btCancelarAltaActionPerformed(null);                    
        }
    }
    }//GEN-LAST:event_btCancelarAltaKeyPressed

    private void btCancelarAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarAltaActionPerformed
        // TODO add your handling code here:
         VistaConsultarArticulosGeneral vista = new VistaConsultarArticulosGeneral(textoBusqueda);
           this.removeAll();
           //this.setBorder(javax.swing.BorderFactory.createEtchedBorder());
           this.setLayout(new java.awt.BorderLayout());          
           this.add(vista);
           vista.show();
           this.revalidate();
           this.repaint();
        
    }//GEN-LAST:event_btCancelarAltaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAceptarAlta;
    private javax.swing.JButton btCancelarAlta;
    private javax.swing.JComboBox comboBoxUnidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txCodigoArticulo;
    private javax.swing.JTextField txDescripcion;
    private javax.swing.JTextField txProveedor;
    private javax.swing.JTextField txcantidadUnidad;
    // End of variables declaration//GEN-END:variables
}
