/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package articulo;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import usuario.ControlUsuario;

/**
 *
 * @author Eddie
 */
public class VistaCompraArticulos extends javax.swing.JPanel {
    private Long idArticulo = null;
    private String textoBusqueda;
    private Long codigoArticulo;

    /**
     * Creates new form VistaCompraArticulos
     */
    public VistaCompraArticulos() {
        initComponents();
    }
    
    public VistaCompraArticulos(Long codigoArticulo, String textoBusqueda)
    {
        initComponents();
        
        this.textoBusqueda = textoBusqueda;
        this.codigoArticulo = codigoArticulo;
        SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
        dateFecha.setDateFormat(formatoFecha);
        //dateFecha.setDateFormat(new DateFormat());
        //Creamos variable para guardar el articulo
        Articulo articulo = null;
        //Creamos controlador articulo
        ControlArticulo ctrArticulo = new ControlArticulo();
        
       articulo = ctrArticulo.buscarUnoPorCodigoArticulo(codigoArticulo);
        
       if(articulo==null)
           JOptionPane.showMessageDialog(this,"Articulo invalido");
       else
       {
           this.idArticulo = articulo.getIdArticulo();
           lbCodigoArticulo.setText(articulo.getCodigoArticulo().toString());
           lbDescripcion.setText(articulo.getDescripcion());
           lbCantidad.setText(articulo.getCantidadExistencia().toString());
           lbPrecioCompraActual.setText(articulo.getPrecioCompra().toString());
           lbPrecioVentaActual.setText(articulo.getPrecioVenta().toString());
           lbCantidadUnidad.setText(articulo.getCantidadUnidad().toString());
           lbUnidad.setText(articulo.getUnidad());
           
       }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        btAceptar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbCodigoArticulo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbDescripcion = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbCantidad = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbPrecioCompraActual = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbPrecioVentaActual = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbCantidadUnidad = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lbUnidad = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txPrecioCompra = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txPrecioVenta = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txCantidad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        dateFecha = new datechooser.beans.DateChooserCombo();

        setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Compra De Artículos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        add(jLabel1, gridBagConstraints);

        btAceptar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/img20x20/aceptar1.png"))); // NOI18N
        btAceptar.setText("Aceptar");
        btAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                realizarCompra(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 248;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 0, 3, 0);
        add(btAceptar, gridBagConstraints);

        btCancelar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/img20x20/cancelar_1.jpg"))); // NOI18N
        btCancelar.setText("Cancelar");
        btCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarCompra(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 237;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 0, 3, 0);
        add(btCancelar, gridBagConstraints);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), null), "Datos Artículo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Código Artículo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.ipady = 1;
        jPanel2.add(jLabel3, gridBagConstraints);

        lbCodigoArticulo.setBackground(new java.awt.Color(204, 204, 204));
        lbCodigoArticulo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbCodigoArticulo.setForeground(new java.awt.Color(0, 0, 255));
        lbCodigoArticulo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 172;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel2.add(lbCodigoArticulo, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Descripción:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 19;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel2.add(jLabel5, gridBagConstraints);

        lbDescripcion.setBackground(new java.awt.Color(204, 204, 204));
        lbDescripcion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbDescripcion.setForeground(new java.awt.Color(0, 0, 255));
        lbDescripcion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 172;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel2.add(lbDescripcion, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Cantidad en Existencia:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel2.add(jLabel6, gridBagConstraints);

        lbCantidad.setBackground(new java.awt.Color(204, 204, 204));
        lbCantidad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbCantidad.setForeground(new java.awt.Color(0, 0, 255));
        lbCantidad.setText(".");
        lbCantidad.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 172;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel2.add(lbCantidad, gridBagConstraints);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Precio Compra Actual:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel2.add(jLabel9, gridBagConstraints);

        lbPrecioCompraActual.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbPrecioCompraActual.setForeground(new java.awt.Color(0, 0, 255));
        lbPrecioCompraActual.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 172;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel2.add(lbPrecioCompraActual, gridBagConstraints);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Precio Venta Actual:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 1;
        jPanel2.add(jLabel11, gridBagConstraints);

        lbPrecioVentaActual.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbPrecioVentaActual.setForeground(new java.awt.Color(0, 0, 255));
        lbPrecioVentaActual.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 172;
        gridBagConstraints.ipady = 5;
        jPanel2.add(lbPrecioVentaActual, gridBagConstraints);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Cantidad Unidad:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel2.add(jLabel10, gridBagConstraints);

        lbCantidadUnidad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbCantidadUnidad.setForeground(new java.awt.Color(0, 0, 255));
        lbCantidadUnidad.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 172;
        gridBagConstraints.ipady = 5;
        jPanel2.add(lbCantidadUnidad, gridBagConstraints);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Unidad:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel2.add(jLabel13, gridBagConstraints);

        lbUnidad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbUnidad.setForeground(new java.awt.Color(0, 0, 255));
        lbUnidad.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 172;
        gridBagConstraints.ipady = 5;
        jPanel2.add(lbUnidad, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 7;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 0, 0);
        add(jPanel2, gridBagConstraints);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), null), "Datos de la compra", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel1.setMaximumSize(null);
        jPanel1.setMinimumSize(null);
        jPanel1.setPreferredSize(null);
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Precio Compra:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanel1.add(jLabel2, gridBagConstraints);

        txPrecioCompra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txPrecioCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txPrecioCompraActionPerformed(evt);
            }
        });
        txPrecioCompra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txPrecioCompraKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(txPrecioCompra, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Precio Venta:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanel1.add(jLabel7, gridBagConstraints);

        txPrecioVenta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.4;
        jPanel1.add(txPrecioVenta, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Cantidad a Comprar:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanel1.add(jLabel8, gridBagConstraints);

        txCantidad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(txCantidad, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Fecha:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanel1.add(jLabel4, gridBagConstraints);

        dateFecha.setWeekStyle(datechooser.view.WeekDaysStyle.SHORT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(dateFecha, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = -11;
        gridBagConstraints.ipady = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(jPanel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void txPrecioCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txPrecioCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txPrecioCompraActionPerformed

    private void realizarCompra(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_realizarCompra
        // TODO add your handling code here:
        String fecha = dateFecha.getSelectedDate().get(Calendar.YEAR)+"-"+(dateFecha.getSelectedDate().get(Calendar.MONTH)+1)+"-"+dateFecha.getSelectedDate().get(Calendar.DAY_OF_MONTH);
        //JOptionPane.showMessageDialog(this, fecha);
        
        String errorString = "";
        
       ControlArticulo ctrArticulos = new ControlArticulo();
       
       String errors = "";
        
      // ControlUsuario ctrUsuario = new ControlUsuario();
       
    // Long idUsuario = ctrUsuario.obtenerUsuarioActual(this);
       
      // Boolean autorizado = ctrUsuario.autorizarOperacion(idUsuario);
       
      // if(!autorizado)
       //    errors += "No estas autorizado";
    
      
    
       errors += ctrArticulos.validaDatosCompraArticulo(txPrecioCompra.getText(), txPrecioVenta.getText(),txCantidad.getText(),fecha );
    
       
       if(errors.length()>0)
       { JOptionPane.showMessageDialog(this,errors);
        //barraEstado.setText("Alta Articulos: En Espera");
       }
       else
       {
        Integer status = ctrArticulos.realizarCompraArticulo(idArticulo.toString(), txPrecioCompra.getText(), txPrecioVenta.getText(),txCantidad.getText(), fecha  );
    
           if(status==1)
           {JOptionPane.showMessageDialog(this,"Compra Exitosa");
           //barraEstado.setText("Alta Articulos: Completado");
           
           VistaConsultarArticuloEspecifico vista = new VistaConsultarArticuloEspecifico(codigoArticulo, textoBusqueda);
           this.removeAll();
           

           //this.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        this.setLayout(new java.awt.BorderLayout());
           
           this.add(vista);
           vista.show();
           this.revalidate();
           this.repaint();
           
           }
           else
           {
               JOptionPane.showMessageDialog(this,"Hubo un error en la operacion");
               //barraEstado.setText("Alta Articulos: En Espera");
           }
           
       }
        
        
    }//GEN-LAST:event_realizarCompra

    private void txPrecioCompraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txPrecioCompraKeyReleased

        Float precioSugerido = null;
        Float porcentajeSugerido = 100f;
        Float precioCompra = null;
        
        try{
        
            precioCompra  = Float.parseFloat(txPrecioCompra.getText());
        
        }catch(NumberFormatException e){
            //txPrecioVenta.setText("0.0");
        }
        
        if(precioCompra==null){
            txPrecioVenta.setText("0.0");
        }
        else
            if(precioCompra<=0){
                txPrecioVenta.setText("0.0");
            }else{
             precioSugerido =  precioCompra+((precioCompra*porcentajeSugerido)/100);
             txPrecioVenta.setText(""+precioSugerido);
            }
       
        
    }//GEN-LAST:event_txPrecioCompraKeyReleased

    private void cancelarCompra(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarCompra
        // TODO add your handling code here:

        VistaConsultarArticulosGeneral vista = new VistaConsultarArticulosGeneral(textoBusqueda);
        this.removeAll();
        //this.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        this.setLayout(new java.awt.BorderLayout());
        this.add(vista);
        vista.show();
        this.revalidate();
        this.repaint();

    }//GEN-LAST:event_cancelarCompra

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAceptar;
    private javax.swing.JButton btCancelar;
    private datechooser.beans.DateChooserCombo dateFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbCantidad;
    private javax.swing.JLabel lbCantidadUnidad;
    private javax.swing.JLabel lbCodigoArticulo;
    private javax.swing.JLabel lbDescripcion;
    private javax.swing.JLabel lbPrecioCompraActual;
    private javax.swing.JLabel lbPrecioVentaActual;
    private javax.swing.JLabel lbUnidad;
    private javax.swing.JTextField txCantidad;
    private javax.swing.JTextField txPrecioCompra;
    private javax.swing.JTextField txPrecioVenta;
    // End of variables declaration//GEN-END:variables
}
